UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-000.jpg' WHERE lower(name) = lower('Cream Table runners');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-001.png' WHERE lower(name) = lower('Tan/brown Runner');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-002.png' WHERE lower(name) = lower('Brown runners');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-003.png' WHERE lower(name) = lower('Dusty blue runners');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-010.png' WHERE lower(name) = lower('Round tablecloth -120in Wht');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-011.png' WHERE lower(name) = lower('Pistachio cheesecloth napkins');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-012.png' WHERE lower(name) = lower('Cream Cheesecloth Napkins');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-012.png' WHERE lower(name) = lower('cream napkins');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-015.png' WHERE lower(name) = lower('White Runners');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-050.png' WHERE lower(name) = lower('Dark blue cheesecloth runners');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-057.png' WHERE lower(name) = lower('Draping cloths - cream burnt orange and rust');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-016.png' WHERE lower(name) = lower('Glass Cup');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-018.png' WHERE lower(name) = lower('Glass Cup - L');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-020.png' WHERE lower(name) = lower('Coupe Glass');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-022.png' WHERE lower(name) = lower('Champagne Flutes');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-024.png' WHERE lower(name) = lower('Vintage Amber bud vases');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-026.png' WHERE lower(name) = lower('Mixed Vintage Pressed Goblets');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-028.png' WHERE lower(name) = lower('Stemless Wine Glass');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-030.png' WHERE lower(name) = lower('Coupe Glass (sm)');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-034.png' WHERE lower(name) = lower('Water Goblets');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-046.png' WHERE lower(name) = lower('Cream plates');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-047.png' WHERE lower(name) = lower('White dessert plates');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-009.png' WHERE lower(name) = lower('Gold Fork - S');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-009.png' WHERE lower(name) = lower('Gold Forks - L');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-009.png' WHERE lower(name) = lower('Gold Knives');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-009.png' WHERE lower(name) = lower('Gold Spoon - L');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-009.png' WHERE lower(name) = lower('Gold Spoon - S');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-031.png' WHERE lower(name) = lower('Dark Metallic Knives');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-031.png' WHERE lower(name) = lower('Large Dark Metallic Fork');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-031.png' WHERE lower(name) = lower('Large Dark Metallic Spoon');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-031.png' WHERE lower(name) = lower('Small Dark Metallic Silverware');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-031.png' WHERE lower(name) = lower('Small Metallic Fork');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-004.png' WHERE lower(name) = lower('Battery-Powered Tapered candles');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-005.png' WHERE lower(name) = lower('2" round candles varying heights');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-035.png' WHERE lower(name) = lower('Gold taper candle holders- various sizes');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-036.png' WHERE lower(name) = lower('clear Glass candle holders');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-040.png' WHERE lower(name) = lower('18inch chimneys');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-041.png' WHERE lower(name) = lower('Gold candle holder');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-042.png' WHERE lower(name) = lower('Tall Glass tea light Candle holders');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-042.png' WHERE lower(name) = lower('tall Glass 2in candle holder');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-044.png' WHERE lower(name) = lower('Hurricanes');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-045.png' WHERE lower(name) = lower('ribbed candle holders');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-065.png' WHERE lower(name) = lower('12" chimney');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-006.png' WHERE lower(name) = lower('Black Umbrella');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-007.png' WHERE lower(name) = lower('9.5 inch white basket');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-007.png' WHERE lower(name) = lower('11in white basket');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-008.png' WHERE lower(name) = lower('Clear umbrellas');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-037.png' WHERE lower(name) = lower('paper umbrellas');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-032.png' WHERE lower(name) = lower('assorted ribbed bud vases');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-033.png' WHERE lower(name) = lower('clear Glass bud vases - various sizes');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-038.png' WHERE lower(name) = lower('Clear Glass bud vases- various heights');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-058.png' WHERE lower(name) = lower('Cement pots - 2 sizes');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-059.png' WHERE lower(name) = lower('terracotta stone pots- 2 sizes');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-060.png' WHERE lower(name) = lower('Aged vase');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-039.png' WHERE lower(name) = lower('Glass Beverage Dispenser');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-049.png' WHERE lower(name) = lower('Gold /glass card box');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-052.png' WHERE lower(name) = lower('Gold acrylic sign holder');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-055.png' WHERE lower(name) = lower('wooden sign holders');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-061.png' WHERE lower(name) = lower('Gold hanging sign Holder');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-051.png' WHERE lower(name) = lower('Wooden crate');
UPDATE inventory_items SET photo_url = 'https://qnnnfbutcsciebimtlgy.supabase.co/storage/v1/object/public/inventory-photos/img-053.png' WHERE lower(name) = lower('aged stone pillers');
